export {default as Nav} from "./Nav"
export {default as Footer} from "./Footer"
export {default as HeroSection} from "./HeroSection"
export {default as ShopProductRange} from "./ShopProductRange"
export {default as FeaturedProduct} from "./FeaturedProduct"
export {default as ExploreDesign} from "./ExploreDesign"
export {default as Infofeatures } from "./Infofeatures"
export {default as CategoryBanner } from "./CategoryBanner"
export {default as SignUpBanner } from "./SignUpBanner"
export {default as ExploreFrame } from "./ExploreFrame"
export {default as ExploreFurniture } from "./ExploreFurniture"
export {default as ExploreHomeDecor } from "./ExploreHomeDecor"
export {default as ExplorePainting } from "./ExplorePainting"
export {default as ProductDetails } from "./ProductDetails"
export {default as AlsoAvailable } from "./AlsoAvailable"
export {default as ReviewCard } from "./ReviewCard"
export {default as SearchResult } from "./SearchResult"
